version: 2

# List of jobs
jobs:
    # The build and test job
    build-test:
        working_directory: ~/lazy-school
        docker:
            - image: circleci/node:8.9.0-browsers
        environment:
            FINGERPRINT: fd:7f:a9:ca:47:78:c5:86:af:eb:76:81:e1:22:5e:a9
            SSH_USER: la
            SSH_HOST: lazy-school.lazy-ants.com
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Install the last version of Google Chrome
            - run:
                name: Update Google Chrome
                command: |
                    sudo apt-get update
                    sudo apt-get install libappindicator3-1 libdbusmenu-gtk3-4 libindicator3-7
                    curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                    sudo dpkg -i google-chrome.deb
                    sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
                    rm google-chrome.deb
            # Install pm2
            - run:
                name: Install pm2
                command: sudo npm install -g pm2
            # Install full-icu
            - run:
                name: Install full-icu
                command: |
                    sudo npm install --unsafe-perm -g full-icu
                    echo 'export NODE_ICU_DATA=/usr/local/lib/node_modules/full-icu' >> ~/.bashrc
                    echo 'export PATH=$NODE_ICU_DATA:$PATH' >> ~/.bashrc
                    source ~/.bashrc
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "project/application/package.json" }}
                - v1-dependencies-
            # Add fingerprint
            - add_ssh_keys:
                fingerprints:
                    - "$FINGERPRINT" #https://circleci.com/docs/2.0/add-ssh-key
            # Keyscan $SSH_HOST (HACK)
            - run:
                name: Keyscan $SSH_HOST (HACK)
                command: ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
            # Copy ng-uikit-pro-standard package from the server
            - run:
                name: Copy ng-uikit-pro-standard package from the server
                command: |
                    scp $SSH_USER@$SSH_HOST:/home/la/lazy-school.lazy-ants.com-assets/ng-uikit-pro-standard-6.2.4.tgz /home/circleci/lazy-school/project/application
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: cd project/application && npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "project/application/package.json" }}
                paths:
                    - project/application/node_modules
            # Build project
            - run:
                name: Building
                command: cd project/application && npm run build:ssr
            # Running the Nodejs server instance
            - run:
                name: Running the instance Nodejs server
                command: cd project/application && npm run serve:ssr
            - run: sleep 15 # workaround pm2 auto restart issue
            # Check the Nodejs server status
            - run:
                name: Check the Nodejs server status
                command: bash pm2-health-check-circleci.sh
            # Stop the Nodejs server
            - run:
                name: Stoping Nodejs server
                command: cd project/application && npm run pm2:stop
            # Lint the source code
            - run:
                name: Linting
                command: cd project/application && npm run lint
            # E2E test
            - run:
                name: E2E Testing
                command: cd project/application && npm run e2e
            # Test the source code
            - run:
                name: Unit Testing
                command: cd project/application && npm run test -- --watch=false
    # The deploy job
    deploy:
        machine:
            enabled: true
        environment:
            FINGERPRINT: fd:7f:a9:ca:47:78:c5:86:af:eb:76:81:e1:22:5e:a9
            SSH_USER: la
            SSH_HOST: lazy-school.lazy-ants.com
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "$FINGERPRINT" #https://circleci.com/docs/2.0/add-ssh-key
            - run:
                name: Deploy Over SSH
                command: |
                    ssh $SSH_USER@$SSH_HOST "cd /var/www/lazy-school && git status && git checkout -- . && git pull origin master && bash deploy-circleci.sh"

workflows:
    version: 2
    # The build, test and deploy
    build-test_deploy:
        jobs:
            - build-test
            - deploy:
                requires:
                    - build-test
                filters:
                    branches:
                        only: master
